version: 0.2

phases:
  build:
    commands:
      - test -s index.html
      - grep -q "<!doctype html>" index.html

artifacts:
  files:
    - index.html
    - appspec.yml
    - restart_httpd.sh
    - validate_service.sh
